services:
  hub:
    image: seleniarm/hub:latest
    ports:
      - 4444:4444
      - 4442:4442
      - 4443:4443

  chrome:
    image: seleniarm/node-chromium:latest
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4

  firefox:
    image: seleniarm/node-firefox:latest
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4

  test-execution:
    image: simtran/automation-tests
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - MAVEN_PROFILE=${MAVEN_PROFILE}
      - GRID_ENABLED=${GRID_ENABLED}
    volumes:
      - ./target/allure-results:/home/web-tests/target/allure-results
      - ./src/main/resources/test-data/data.xlsx:/home/web-tests/src/main/resources/test-data/data.xlsx